-- Get the DDL for the table
--select GET_DDL ('TABLE', 'EDP_META_DB. EDP_ETL_METADATA.ETL_PIPELINE_RUN_HISTORY_LOG");
-- Rename Orginal SNF table
alter table EDP_META_DB.EDP_ETL_METADATA.ETL_PIPELINE_RUN_HISTORY_LOG rename to EDP_META_DB.EDP_ETL_METADATA.ETL_PIPELINE_RUN_HISTORY_LOG_REPLICATION;
-- Modify the defintion from previous to set the PRIMARY KEY create or replace HYBRID TABLE ETL_PIPELINE_RUN_HISTORY_LOG (
PIPELINE_RUN_ID NUMBER(38, 0) NOT NULL PRIMARY KEY, PIPELINE_ID NUMBER(38,0) NOT NULL, DOMAIN_ID NUMBER (38,0) NOT NULL, PROVIDER_SOURCE_ID NUMBER (38,0) NOT NULL, ORCHESTRATION_PIPELINE_NM VARCHAR (250),
ORCHESTRATION_PIPELINE_RUN_CD VARCHAR (250) ,
PIPELINE_START_DT TIMESTAMP_NTZ(9), PIPELINE_END_DT TIMESTAMP_NTZ(9), PIPELINE_RUN_STATUS VARCHAR (80) ,
LAST_UPDATED_BY VARCHAR(100) DEFAULT CURRENT_USER () ,
LAST_UPDATE_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() ,
VERSION_NM VARCHAR (250) ,
PIPELINE_EXCEPTION_DESC VARCHAR (16777216) ,
PARENT_ORCHESTRATION_PIPELINE_NM VARCHAR (250) ,
PARENT_ORCHESTRATION_PIPELINE_RUN_CD VARCHAR (250),
ADOPTER_ID NUMBER (38,01.
CALENDAR_FL VARCHAR (1) ,
CALENDAR_CODE VARCHAR (100) ,
CALENDAR_BUSINESS_DAY_TAG VARCHAR (100),
SCHEDULE_TIMEZONE VARCHAR (100),
TIMEZONE_OFFSET VARCHAR (10)
);

-- Copy data into Hybrid table. There were duplicates records in the original table which should not have been present.  
insert into ETL_PIPELINE_RUN_HISTORY_LOG select * from ETL_PIPELINE_RUN_HISTORY_LOG_REPLICATION where pipeline_run_id != 0;
